ALTER TABLE Category
ADD COLUMN created_by VARCHAR(255),
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_by VARCHAR(255),
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN deleted_by VARCHAR(255),
ADD COLUMN deleted_at TIMESTAMP,
ADD COLUMN version BIGINT;

ALTER TABLE Customer
ADD COLUMN created_by VARCHAR(255),
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_by VARCHAR(255),
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN deleted_by VARCHAR(255),
ADD COLUMN deleted_at TIMESTAMP,
ADD COLUMN version BIGINT;

ALTER TABLE Invoice
ADD COLUMN created_by VARCHAR(255),
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_by VARCHAR(255),
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN deleted_by VARCHAR(255),
ADD COLUMN deleted_at TIMESTAMP,
ADD COLUMN version BIGINT;

ALTER TABLE InvoiceItem
ADD COLUMN created_by VARCHAR(255),
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_by VARCHAR(255),
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN deleted_by VARCHAR(255),
ADD COLUMN deleted_at TIMESTAMP,
ADD COLUMN version BIGINT;

ALTER TABLE Payment
ADD COLUMN created_by VARCHAR(255),
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_by VARCHAR(255),
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN deleted_by VARCHAR(255),
ADD COLUMN deleted_at TIMESTAMP,
ADD COLUMN version BIGINT;

ALTER TABLE Product
ADD COLUMN created_by VARCHAR(255),
ADD COLUMN updated_by VARCHAR(255),
ADD COLUMN deleted_by VARCHAR(255),
ADD COLUMN deleted_at TIMESTAMP,
ADD COLUMN version BIGINT;

ALTER TABLE Setting
ADD COLUMN created_by VARCHAR(255),
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_by VARCHAR(255),
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN deleted_by VARCHAR(255),
ADD COLUMN deleted_at TIMESTAMP,
ADD COLUMN version BIGINT;

ALTER TABLE Tax
ADD COLUMN created_by VARCHAR(255),
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_by VARCHAR(255),
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN deleted_by VARCHAR(255),
ADD COLUMN deleted_at TIMESTAMP,
ADD COLUMN version BIGINT;

